amqstreams:
  applicationName: amqstreams
  applicationNamespace: openshift-gitops
  destinationNamespace: kafka
  source:
    repoUrl:
    targetRevision:
    path:
    helm:
      values:
        kafka:
          enabled: true
        console:
          enabled: true

        kafka-broker:
          namespace:
          nameOverride: kafka
          kafka:
            controller:
              enabled: true
            listener:
              external:
                tls:
                  secret:
                    value:
                      crt: 
                      key: 
          authentication:
            clientId:
            clientSecret: 
            securityProtocol: SASL_SSL
            saslMechanism: SCRAM-SHA-512
        amq-streams-console:
          namespace: 
          subdomain: 
          kafka:
            name: kafka
            namespace: 
            authentication:
              saslMechanism: SASL_SSL
              securityProtocol: SCRAM-SHA-512
            authorization: simple
        kafka-topics:
          kafka:
            namespace: 
            cluster: kafka
  argocd:
    enabled: true
    syncwave: "1"

keycloak:
  applicationName: keycloak
  applicationNamespace: openshift-gitops
  destinationNamespace: keycloak
  source:
    repoUrl: 
    targetRevision:
    path:
    helm:
      values:
        keycloak:
          nameOverride: keycloak
          route:
            host:
          ingress:
            enabled: false
  argocd:
    enabled: true
    syncwave: "1"