{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "review-service.serviceAccountName" . }}
  labels:
    {{- include "review-service.labels" . | nindent 4 }}
  annotations:
    {{- include "review-service.argocd-syncwave" . | nindent 4 }}
{{- end }}
