{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  annotations:
    {{- include "minio.argocd-syncwave" . | nindent 4 }}
{{- end }}
