version: 4.0.0
image: registry.redhat.io/amq-streams/kafka-40-rhel9@sha256:4bdc5d9e8a800e2abc972b1cc09ca8dec91ebce34616e43fe16df86f02ec9d0f
replicas: 1
topicPrefix: globex-ai-cdc
keyConverter: org.apache.kafka.connect.json.JsonConverter
valueConverter: org.apache.kafka.connect.json.JsonConverter
replicationFactor: 3
authentication:
  passwordKey: clientSecret
resources:
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 500m
    memory: 1Gi
livenessProbe:
  initialDelaySeconds: 45
  timeoutSeconds: 5
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5

kafka:
  bootstrapServer: ""
  securityProtocol: ""
  saslMechanism: ""
  clientId: ""

argocd:
  enabled: true
  syncwave: "0"
