---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.globexai.applicationName }}
  namespace: {{ .Values.globexai.applicationNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.globexai.argocd.syncwave }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: ""
    namespace: {{ .Values.globexai.destinationNamespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  source:
    repoURL: {{ .Values.globexai.source.repoUrl }}
    targetRevision: {{ .Values.globexai.source.targetRevision }}
    path: {{ .Values.globexai.source.path }}
    helm:
      valuesObject:
        {{ toYaml .Values.globexai.source.helm.values | nindent 8 }}