apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.name" . }}-config
  labels:
    {{- include "mimir.labels" (dict "ctx" .) | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  mimir.yaml: |
    {{ include "mimir.calculatedConfig" . | nindent 4 }}
