apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.name" . }}-headless
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "mimir" "memberlist" true) | nindent 4 }}
    prometheus.io/service-monitor: "false"
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ include "mimir.serverHttpListenPort" .}}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ include "mimir.serverGrpcListenPort" . }}
      protocol: TCP
      name: grpc
      targetPort: grpc
    {{- if .Values.service.extraPorts }}
    {{- toYaml .Values.service.extraPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "mimir.selectorLabels" (dict "ctx" . "component" "mimir" "memberlist" true) | nindent 4 }}
  publishNotReadyAddresses: true
