minio:
  enabled: true
  nameOverride: minio
  rootUser: grafana-mimir
  rootPassword: supersecret
  argocd:
    enabled: true
    syncwave: "-2"
    hook:
      syncwave: "-1"

mimir:
  enabled: true
  minio:
    enabled: true
    name: minio
    rootUser: grafana-mimir
    rootPassword: supersecret

tempo:
  enabled: true

loki:
  enabled: true
